// Primitive data types
/* 
  Data Types
In the previous section, we mentioned a little bit about data types. Data or values have data types. Data types describe the characteristics of data. Data types can be divided into two:

Primitive data types
Non-primitive data types(Object References)
Primitive Data Types
Primitive data types in JavaScript include:

Numbers - Integers, floats
Strings - Any data under single quote, double quote or backtick quote
Booleans - true or false value
Null - empty value or no value
Undefined - a declared variable without a value
Symbol - A unique value that can be generated by Symbol constructor
Non-primitive data types in JavaScript includes:

Objects
Arrays
Now, let us see what exactly primitive and non-primitive data types mean. Primitive data types are immutable(non-modifiable) data types. Once a primitive data type is created we cannot modify it.
*/

// Example: 
let word = 'javaScript'
word[0] = 'y'
console.log(word)


let numOne = 3
let numTwo = 3

console.log(numOne === numTwo)

let js = 'javaScript'
let py = 'Python'
console.log(js === py)

// Non-Primitive Data Types

let nums = [1, 2, 3]
nums[0] = 10
console.log(nums)

let numsOne = [1, 2, 3]
let numbers = [1, 2, 3]
let compare = numsOne === numbers
console.log(compare)

let userOne = {
    name: 'Cordeiro',
    role: 'Software Enginer',
    country: 'Angola'
}

let userTwo = {
    name: 'Luis',
    role: 'QA',
    country: 'Angola'
}
console.log(userOne === userTwo)

// Numbers 
// Math Objects
const PI = Math.PI
console.log(PI.toFixed(2))

console.log(Math.round(PI))

console.log(Math.round(9.81))
console.log(Math.floor(PI))
console.log(Math.ceil(PI))

//  returns the maximumu value  
console.log(Math.max(-5, 3, 20, 4, 5, 10))
//  returns the minimum value
console.log(Math.min(-5, 3, 20, 4, 5, 10))
// creates random number between 0 to 0.999999
const randNum = Math.random()
console.log(randNum.toFixed(1))

// 
// Let us  create random number between 0 to 10
const num = Math.floor(Math.random() * 10)
console.log(num)
console.log("==================")
// //Absolute value
const number = -20;
console.log(Math.abs(number))
console.log("==================")

console.log("==================")
// Square root
console.log(Math.sqrt(100))
console.log(Math.sqrt(2).toFixed(2))
console.log("==================")

console.log("==================")
// Power
console.log(Math.pow(3, 3))
console.log(Math.pow(2, 3))
console.log("==================")

console.log("==================")
// Random Number Generator
let randomNum = Math.random()
let numBtnZeroAndTen = randomNum * 11
console.log(numBtnZeroAndTen.toFixed(1))
console.log("==================")

// Strings
let space = ' ';
let firstName = 'Cordeiro';
let lastName = 'Luis';
let age = 234;
let country = 'Angola';
let city = 'Luanda';
let language = 'javaScript';
let job = 'Software Enginer';
let quote = "The saying, 'Seeing is Believing' is not correct in 2020.";
let quoteWithBackTick = `The 'saying is Believing' is not 2020. `

// String concatenation 
let fullName = firstName + space + lastName + space
console.log(fullName)

let personInfo = fullName + '. I am ' + age + '. I live in ' + country
console.log(personInfo)

// Long Literal Strings

const paragraph = "My name is Cordeiro Luis. I live in Angola, Luanda.\ I am a software enginer. I work with HTML, CSS, JavaScript, React, Redux and NodeJs. In the end of 2019, i was thinking to expand my teaching and reach\ to global audience and i started a python Challenge from November 20 - December 19. It was one of the most rewarding and inspiring experiênce.\ Now, we are in 2024. I am enjoying preparing the 30DaysOfJavaScript challenge I hope you are enjoying too."
console.log(paragraph)

console.log("=============================================")
console.log(`I hope everyone is enjoying the 30 days of javaScript challenge. \nDo you?`)
console.log('Days\tTopics\tExercises')
console.log('Day 1\t3\t5')
console.log('Day 2\t3\t5')
console.log('Day 3\t3\t5')
console.log('Day 4\t3\t5')
console.log('\\')
console.log('\\')

console.log("=============================================")
// Template String 
   console.log(`The sum of 2 and 3 is 5`)
   let a = 2
   let b = 3
   console.log(`The sum of ${a} and ${b} is ${a + b}`)
   console.log(`${a} is greater than ${b}: ${a > b}`)
console.log("=============================================")
